apiVersion: v1
kind: Service
metadata:
  name: portfolio-website-service
spec:
  selector:
    app: portfolio-website
  type: NodePort
  ports:
    - protocol: TCP
      port: 80 # Service port
      targetPort: 80 # Container port
