---
- name: Deploy Static Website
  hosts: webserver
  become: yes
  vars:
    web_root: /var/www/html

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start and enable Nginx
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Remove default Nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Create web root directory
      file:
        path: "{{ web_root }}"
        state: directory
        owner: www-data
        group: www-data
        mode: "0755"

    - name: Copy website files
      synchronize:
        src: ../website/
        dest: "{{ web_root }}/"
        delete: yes
        recursive: yes
      delegate_to: localhost

    - name: Set proper permissions
      file:
        path: "{{ web_root }}"
        owner: www-data
        group: www-data
        recurse: yes

    - name: Configure Nginx site
      copy:
        content: |
          server {
              listen 80 default_server;
              listen [::]:80 default_server;
              
              root {{ web_root }};
              index index.html;
              
              server_name _;
              
              location / {
                  try_files $uri $uri/ =404;
              }
          }
        dest: /etc/nginx/sites-available/website
        owner: root
        group: root
        mode: "0644"

    - name: Enable Nginx site
      file:
        src: /etc/nginx/sites-available/website
        dest: /etc/nginx/sites-enabled/website
        state: link

    - name: Test Nginx configuration
      command: nginx -t
      register: nginx_test
      changed_when: false

    - name: Reload Nginx
      systemd:
        name: nginx
        state: reloaded
      when: nginx_test.rc == 0

    - name: Allow Nginx through UFW
      ufw:
        rule: allow
        name: "Nginx Full"

    - name: Enable UFW
      ufw:
        state: enabled
        policy: deny
        direction: incoming

    - name: Allow SSH through UFW
      ufw:
        rule: allow
        port: "22"
        proto: tcp
