name: Deploy Website to AWS

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  TF_VERSION: 1.6.0

jobs:
  terraform:
    name: Terraform Infrastructure
    runs-on: ubuntu-latest
    outputs:
      instance_ip: ${{ steps.tf_output.outputs.ip }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: ./terraform
        run: |
          terraform plan \
            -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}" \
            -out=tfplan

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve tfplan

      - name: Get Terraform Outputs
        id: tf_output
        working-directory: ./terraform
        run: |
          echo "ip=$(terraform output -raw public_ip)" >> $GITHUB_OUTPUT

      - name: Wait for instance to be ready
        run: |
          echo "Waiting 60 seconds for instance to be ready..."
          sleep 60

  deploy:
    name: Deploy with Ansible
    needs: terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ needs.terraform.outputs.instance_ip }} >> ~/.ssh/known_hosts

      - name: Create Ansible inventory
        working-directory: ./ansible
        run: |
          cat > inventory.ini << EOF
          [webserver]
          web ansible_host=${{ needs.terraform.outputs.instance_ip }}

          [webserver:vars]
          ansible_user=ubuntu
          ansible_ssh_private_key_file=~/.ssh/id_rsa
          ansible_python_interpreter=/usr/bin/python3
          EOF

      - name: Run Ansible Playbook
        working-directory: ./ansible
        run: |
          ansible-playbook -i inventory.ini playbook.yml

      - name: Deployment Success
        run: |
          echo "🎉 Deployment successful!"
          echo "Website URL: http://${{ needs.terraform.outputs.instance_ip }}"
